"""Daily State Intelligence Brief — data builder.

Assembles the full A–I report (+ extras) for a persona's primary state over a 24h
window with 24h-prior deltas. Every section is real, corpus-grounded data; the
narrative prose (exec summary, themed developments, sentiment read, recommended
actions) is generated by one LLM call with a deterministic template fallback.

Universe = articles datelined to the persona's primary state (article_districts),
source_country='IN', last 48h (so we can diff last-24h vs the 24h before).
"""
from __future__ import annotations

import json
import logging
from typing import Any

from sqlalchemy import text

import i18n
from map_page import STATE_CODE
from posture import POL, principal_of

logger = logging.getLogger("report_builder")

# topic_category -> the six risk domains
DOMAIN_TOPICS = {
    "Political / Social": ["POLITICS", "GOVERNANCE", "SOCIAL"],
    "Law & Order": ["SECURITY", "LEGAL"],
    "Health": ["HEALTH"],
    "Economy": ["BUSINESS", "FINANCE"],
    "Infrastructure": ["INFRASTRUCTURE"],
    "Environment": ["ENVIRONMENT", "AGRICULTURE"],
}
# topic_category -> stakeholder group affected
STAKEHOLDER_TOPICS = {
    "Farmers / rural": ["AGRICULTURE", "ENVIRONMENT"],
    "Public / patients": ["HEALTH"],
    "Industry / business": ["BUSINESS", "FINANCE"],
    "Commuters / residents": ["INFRASTRUCTURE"],
    "Citizens / legal": ["LEGAL", "SECURITY"],
}
STATE_NAMES = {"AP": "Andhra Pradesh", "TG": "Telangana", "KA": "Karnataka", "TN": "Tamil Nadu"}


def _primary_state(prefs: dict[str, Any]) -> str:
    for s in (prefs.get("regions") or {}).get("states", []):
        code = STATE_CODE.get((s or "").strip().lower())
        if code:
            return code
    return "AP"


def _severity(n24: int, nprev: int, neg: int) -> str:
    adv = neg / n24 if n24 else 0.0
    vel = n24 / nprev if nprev else (2.0 if n24 else 0.0)
    if n24 >= 20 and adv >= 0.45:
        return "CRITICAL"
    if n24 >= 8 and (adv >= 0.30 or (adv >= 0.18 and vel >= 1.4)):
        return "HIGH"
    if n24 >= 5 and (adv >= 0.10 or vel >= 1.3):
        return "MODERATE"
    return "LOW"


async def _scalar(db, sql: str, p: dict | None = None):
    return (await db.execute(text(sql), p or {})).scalar()


async def build_report(db, prefs: dict[str, Any]) -> dict[str, Any]:
    sc = _primary_state(prefs)
    state_name = STATE_NAMES.get(sc, sc)
    _, principal = principal_of(prefs)
    N = "analytics.now_sim()"

    await db.execute(text("DROP TABLE IF EXISTS _rep"))
    await db.execute(text(f"""
        CREATE TEMP TABLE _rep AS
        SELECT DISTINCT a.id, a.topic_category tc, a.collected_at ca, a.title, a.language_iso lang,
               a.url, a.thumbnail_url thumb, a.summary_preview sp, a.geo_primary geo, a.source_id,
               (SELECT avg(({POL}) * st.intensity) FROM article_stances st WHERE st.article_id = a.id) lean
          FROM article_districts ad JOIN districts d ON d.id = ad.district_id
          JOIN articles a ON a.id = ad.article_id
         WHERE d.state_code = :sc AND a.source_country = 'IN'
           AND a.collected_at >= {N} - interval '48 hours'
    """), {"sc": sc})
    await db.execute(text("CREATE INDEX ON _rep (ca)"))

    n24 = int(await _scalar(db, f"SELECT count(*) FROM _rep WHERE ca >= {N} - interval '24 hours'") or 0)
    nprev = int(await _scalar(db, f"SELECT count(*) FROM _rep WHERE ca < {N} - interval '24 hours'") or 0)
    now = await _scalar(db, f"SELECT {N}")

    # ── domains / risk heatmap ──
    dom_rows = (await db.execute(text(f"""
        SELECT tc,
               count(*) FILTER (WHERE ca >= {N} - interval '24 hours') n24,
               count(*) FILTER (WHERE ca <  {N} - interval '24 hours') nprev,
               count(*) FILTER (WHERE ca >= {N} - interval '24 hours' AND lean <= -0.1) neg
          FROM _rep WHERE tc IS NOT NULL GROUP BY 1
    """))).fetchall()
    by_topic = {r.tc: {"n24": int(r.n24), "nprev": int(r.nprev), "neg": int(r.neg)} for r in dom_rows}
    domains = []
    for dom, topics in DOMAIN_TOPICS.items():
        a = sum(by_topic.get(t, {}).get("n24", 0) for t in topics)
        b = sum(by_topic.get(t, {}).get("nprev", 0) for t in topics)
        ng = sum(by_topic.get(t, {}).get("neg", 0) for t in topics)
        domains.append({"domain": dom, "n24": a, "nprev": b, "neg": ng,
                        "severity": _severity(a, b, ng),
                        "adverse_pct": round(100 * ng / a) if a else 0,
                        "delta_pct": round(100 * (a - b) / b) if b else 0})
    sev_rank = {"CRITICAL": 0, "HIGH": 1, "MODERATE": 2, "LOW": 3}
    domains.sort(key=lambda d: (sev_rank[d["severity"]], -d["n24"]))

    # ── sentiment ──
    s = (await db.execute(text(f"""
        SELECT count(*) FILTER (WHERE lean >= 0.1) pos, count(*) FILTER (WHERE lean <= -0.1) neg,
               count(*) FILTER (WHERE lean > -0.1 AND lean < 0.1) neu
          FROM _rep WHERE ca >= {N} - interval '24 hours'
    """))).fetchone()
    pos, neu, neg = int(s.pos), int(s.neu), int(s.neg)
    scored = pos + neu + neg or 1
    net_pct = round(100 * (pos - neg) / scored)

    # ── districts ──
    dd = (await db.execute(text(f"""
        SELECT d.name nm,
               count(DISTINCT a.id) FILTER (WHERE a.collected_at >= {N} - interval '24 hours') n24,
               count(DISTINCT a.id) FILTER (WHERE a.collected_at <  {N} - interval '24 hours') nprev,
               count(DISTINCT a.id) FILTER (WHERE a.collected_at >= {N} - interval '24 hours'
                     AND EXISTS (SELECT 1 FROM article_stances st WHERE st.article_id = a.id AND ({POL}) < 0)) neg
          FROM article_districts ad JOIN districts d ON d.id = ad.district_id JOIN articles a ON a.id = ad.article_id
         WHERE d.state_code = :sc AND a.source_country = 'IN' AND a.collected_at >= {N} - interval '48 hours'
         GROUP BY 1 ORDER BY 2 DESC LIMIT 10
    """), {"sc": sc})).fetchall()
    districts = [{"name": r.nm.title(), "n24": int(r.n24), "nprev": int(r.nprev), "neg": int(r.neg),
                  "delta_pct": round(100 * (int(r.n24) - int(r.nprev)) / int(r.nprev)) if r.nprev else 0}
                 for r in dd]

    # ── top stories (bilingual, with thumbnail) ──
    ts = (await db.execute(text(f"""
        SELECT r.title, r.lang, s.name src, s.source_tier tier, r.thumb, r.url, r.sp, r.geo, r.lean, r.ca
          FROM _rep r JOIN sources s ON s.id = r.source_id
         WHERE r.ca >= {N} - interval '24 hours'
         ORDER BY (r.thumb IS NOT NULL) DESC, r.ca DESC LIMIT 6
    """))).fetchall()
    top = [{"title": r.title, "lang": r.lang, "source": r.src, "tier": r.tier, "thumb": r.thumb,
            "url": r.url, "summary": (r.sp or "").strip(), "geo": r.geo,
            "tone": "supportive" if (r.lean or 0) >= 0.1 else "hostile" if (r.lean or 0) <= -0.1 else "neutral"}
           for r in ts]
    await i18n.attach_en(db, top, "title")

    # ── quotes (bilingual) ──
    qs = (await db.execute(text(f"""
        SELECT q.quote_text q, NULLIF(q.quote_text_en,'') qen, COALESCE(q.speaker_name_en, q.speaker_name) who, s.name src
          FROM article_quotes q JOIN _rep r ON r.id = q.article_id JOIN sources s ON s.id = r.source_id
         WHERE r.ca >= {N} - interval '24 hours' AND q.speaker_name IS NOT NULL
           AND length(COALESCE(q.quote_text_en, q.quote_text)) BETWEEN 24 AND 200
         ORDER BY r.ca DESC LIMIT 5
    """))).fetchall()
    quotes = [{"q": r.q, "q_en": (r.qen if (r.qen and r.qen != r.q) else None), "who": r.who or "—", "src": r.src} for r in qs]
    await i18n.attach_en(db, quotes, "q")

    # ── figures ──
    fg = (await db.execute(text(f"""
        SELECT an.value v, an.unit u, an.context c FROM article_numbers an JOIN _rep r ON r.id = an.article_id
         WHERE r.ca >= {N} - interval '24 hours' AND an.unit IS NOT NULL AND length(an.context) BETWEEN 10 AND 120
         ORDER BY r.ca DESC LIMIT 6
    """))).fetchall()
    figures = [{"value": str(r.v), "unit": r.u, "context": r.c} for r in fg]

    # ── source intelligence ──
    tiers = [{"tier": r.tier, "stories": int(r.n), "outlets": int(r.outlets)} for r in (await db.execute(text(f"""
        SELECT s.source_tier tier, count(DISTINCT r.id) n, count(DISTINCT s.id) outlets
          FROM _rep r JOIN sources s ON s.id = r.source_id WHERE r.ca >= {N} - interval '24 hours'
         GROUP BY 1 ORDER BY 1
    """))).fetchall()]
    top_outlets = [{"name": r.nm, "tier": r.tier, "health": round(float(r.h or 0), 2), "n": int(r.n)} for r in (await db.execute(text(f"""
        SELECT s.name nm, s.source_tier tier, s.health_score h, count(DISTINCT r.id) n
          FROM _rep r JOIN sources s ON s.id = r.source_id WHERE r.ca >= {N} - interval '24 hours'
         GROUP BY 1,2,3 ORDER BY 4 DESC LIMIT 6
    """))).fetchall()]

    # ── entities / drivers (for stakeholders) ──
    drivers = [{"name": r.nm, "type": r.et, "n": int(r.n)} for r in (await db.execute(text(f"""
        SELECT ed.canonical_name nm, ed.entity_type et, count(DISTINCT m.article_id) n
          FROM article_entity_mentions m JOIN _rep r ON r.id = m.article_id
          JOIN entity_dictionary ed ON ed.id = m.entity_id
         WHERE r.ca >= {N} - interval '24 hours' AND ed.entity_type IN ('person','organization')
         GROUP BY 1,2 ORDER BY 3 DESC LIMIT 8
    """))).fetchall()]
    affected = []
    for grp, topics in STAKEHOLDER_TOPICS.items():
        cnt = sum(by_topic.get(t, {}).get("n24", 0) for t in topics)
        if cnt:
            affected.append({"group": grp, "n": cnt})
    affected.sort(key=lambda x: -x["n"])

    # ── early-warning (rising topics + districts) ──
    early = []
    for t, v in sorted(by_topic.items(), key=lambda x: -(x[1]["n24"])):
        if v["n24"] >= 5 and v["nprev"] and v["n24"] / v["nprev"] >= 1.35:
            early.append({"label": t.title(), "kind": "topic", "now": v["n24"], "prior": v["nprev"],
                          "growth": round(100 * (v["n24"] - v["nprev"]) / v["nprev"])})
    for d in districts:
        if d["n24"] >= 8 and d["nprev"] and d["n24"] / d["nprev"] >= 1.35:
            early.append({"label": d["name"], "kind": "district", "now": d["n24"], "prior": d["nprev"], "growth": d["delta_pct"]})
    early.sort(key=lambda x: -x["growth"])
    early = early[:5]

    # ── themed development clusters (data; LLM writes the prose) ──
    themes = await _themes(db, sc, N)

    structured = {
        "state": state_name, "state_code": sc, "principal": principal,
        "generated_at": str(now), "window_hours": 24,
        "kpis": {"n24": n24, "nprev": nprev, "delta_pct": round(100 * (n24 - nprev) / nprev) if nprev else 0,
                 "net_sentiment": net_pct, "pos": pos, "neu": neu, "neg": neg,
                 "districts_active": len(districts), "adverse_pct": round(100 * neg / scored)},
        "domains": domains, "sentiment": {"pos": pos, "neu": neu, "neg": neg, "net_pct": net_pct},
        "districts": districts, "top_stories": top, "quotes": quotes, "figures": figures,
        "source_intel": {"tiers": tiers, "top_outlets": top_outlets},
        "stakeholders": {"affected": affected, "drivers": drivers},
        "early_warning": early, "themes": themes,
        "confidence": "HIGH" if n24 >= 120 else "MODERATE" if n24 >= 40 else "LOW",
    }
    structured["narrative"] = await _narrate(structured)
    return structured


async def _themes(db, sc: str, N: str) -> list[dict[str, Any]]:
    """Top representative stories per theme (keyword/topic), for the LLM to write up."""
    THEME_DEFS = [
        ("Party & political friction", "tc IN ('POLITICS') AND lean <= -0.05"),
        ("Governance & policy", "tc IN ('GOVERNANCE') OR title ~* '(scheme|cabinet|policy|project|launch|sanction|grant)'"),
        ("Courts & law", "tc IN ('LEGAL') OR title ~* '(court|verdict|bail|petition|case|arrest|probe)'"),
        ("Crime & security", "tc IN ('SECURITY') OR title ~* '(murder|attack|police|seized|smuggl|assault)'"),
        ("Economy & markets", "tc IN ('BUSINESS','FINANCE')"),
        ("Environment & natural", "tc IN ('ENVIRONMENT','AGRICULTURE') OR title ~* '(rain|flood|heat|cyclone|drought|crop)'"),
    ]
    out = []
    for label, cond in THEME_DEFS:
        rows = (await db.execute(text(f"""
            SELECT r.title, s.name src, r.sp, r.geo, r.lean
              FROM _rep r JOIN sources s ON s.id = r.source_id
             WHERE r.ca >= {N} - interval '24 hours' AND ({cond})
             ORDER BY r.ca DESC LIMIT 4
        """))).fetchall()
        if len(rows) >= 2:
            items = [{"title": r.title, "src": r.src, "summary": (r.sp or "").strip(), "geo": r.geo} for r in rows]
            await i18n.attach_en(db, items, "title")
            out.append({"theme": label, "count": len(rows), "items": items})
    return out[:4]


def _facts_blob(s: dict[str, Any]) -> str:
    lines = [f"STATE: {s['state']} (principal desk: {s['principal']})",
             f"VOLUME: {s['kpis']['n24']} stories in 24h vs {s['kpis']['nprev']} prior ({s['kpis']['delta_pct']:+d}%).",
             f"SENTIMENT: {s['sentiment']['pos']} supportive / {s['sentiment']['neu']} neutral / {s['sentiment']['neg']} critical (net {s['sentiment']['net_pct']:+d}%)."]
    lines.append("RISK DOMAINS: " + "; ".join(f"{d['domain']}={d['severity']} ({d['n24']} stories, {d['adverse_pct']}% adverse, {d['delta_pct']:+d}% vs prior)" for d in s["domains"]))
    lines.append("TOP DISTRICTS: " + ", ".join(f"{d['name']} {d['n24']}({d['delta_pct']:+d}%)" for d in s["districts"][:6]))
    if s["early_warning"]:
        lines.append("RISING: " + ", ".join(f"{e['label']} {e['prior']}->{e['now']} (+{e['growth']}%)" for e in s["early_warning"]))
    for th in s["themes"]:
        heads = " | ".join((it.get("title_en") or it["title"]) + (f" — {it['summary']}" if it.get("summary") else "") for it in th["items"][:3])
        lines.append(f"THEME [{th['theme']}]: {heads}")
    if s["figures"]:
        lines.append("FIGURES: " + "; ".join(f"{f['value']} {f['unit']} ({f['context']})" for f in s["figures"][:5]))
    return "\n".join(lines)


_SYS = (
    "You are a senior state-intelligence analyst writing a confidential daily brief for a "
    "political principal's desk. Write in crisp, authoritative, knowledge-rich prose — the voice "
    "of a Stratfor/BBC-Monitoring analyst. Be specific and interpretive: say what happened, why it "
    "matters to the state, and what the second-order risk or opportunity is. Do NOT add citations, "
    "source names in brackets, or hedging boilerplate. Never invent specific numbers beyond those "
    "provided, but you MAY interpret and connect them freely.\n\n"
    "Return ONLY valid JSON with this exact shape:\n"
    "{\n"
    '  "exec_summary": [ "<6-7 punchy bullets, each one rich sentence, on what changed in 24h and why it matters>" ],\n'
    '  "hotspot_read": "<2-3 sentences interpreting the district geography>",\n'
    '  "sentiment_narrative": "<3-4 sentences on tone, polarisation, and any narrative divergence>",\n'
    '  "developments": [ {"theme": "<theme>", "headline": "<rewritten sharp headline>", "body": "<3-4 detailed sentences contextualising the cluster>"} ],\n'
    '  "actions": [ "<5 concrete, prioritised recommended actions tied to the signals>" ]\n'
    "}\n"
    "Make developments cover the themes provided. Make it genuinely useful, not generic."
)


def _templates(s: dict[str, Any]) -> dict[str, Any]:
    """Deterministic fallback if the LLM is unavailable."""
    k = s["kpis"]
    top_dom = s["domains"][0]
    exec_s = [
        f"Coverage {('rose' if k['delta_pct'] > 0 else 'cooled')} {abs(k['delta_pct'])}% ({k['n24']} vs {k['nprev']} stories) over the last 24 hours.",
        f"Net sentiment is {k['net_sentiment']:+d}% — {s['sentiment']['pos']} supportive against {s['sentiment']['neg']} critical pieces.",
        f"{top_dom['domain']} is the day's hottest domain ({top_dom['severity']}, {top_dom['adverse_pct']}% adverse).",
    ]
    if s["districts"]:
        d0 = s["districts"][0]
        exec_s.append(f"{d0['name']} leads district coverage with {d0['n24']} stories.")
    for e in s["early_warning"][:2]:
        exec_s.append(f"{e['label']} is rising fast — {e['prior']}→{e['now']} ({e['growth']:+d}%).")
    devs = [{"theme": t["theme"], "headline": (t["items"][0].get("title_en") or t["items"][0]["title"]),
             "body": " ".join(it.get("summary") or "" for it in t["items"][:2]).strip() or "Multiple stories in this theme this window."}
            for t in s["themes"]]
    actions = [f"Monitor {top_dom['domain']} — the highest-adverse domain today."]
    for e in s["early_warning"][:2]:
        actions.append(f"Track the {e['label']} surge (+{e['growth']}%) over the next 48 hours.")
    actions.append("Hold on low-severity domains; preserve attention for the amber board.")
    return {"exec_summary": exec_s, "hotspot_read": "Coverage concentrates in the busiest districts; watch the fastest risers.",
            "sentiment_narrative": f"Tone is net {k['net_sentiment']:+d}%, with negativity concentrated in the higher-severity domains.",
            "developments": devs, "actions": actions}


async def _narrate(s: dict[str, Any]) -> dict[str, Any]:
    try:
        from groq_client import generate
        raw = await generate(system=_SYS, user=_facts_blob(s), task_type="brief_generation")
        txt = raw.strip()
        i, j = txt.find("{"), txt.rfind("}")
        data = json.loads(txt[i:j + 1])
        if not data.get("exec_summary"):
            raise ValueError("empty exec_summary")
        # backfill any missing keys from templates
        tpl = _templates(s)
        for key in ("exec_summary", "hotspot_read", "sentiment_narrative", "developments", "actions"):
            if not data.get(key):
                data[key] = tpl[key]
        data["_source"] = "llm"
        return data
    except Exception as exc:  # noqa: BLE001 — degrade to templates, never fail the report
        logger.warning("report narrate: LLM unavailable (%s); using templates", exc)
        d = _templates(s)
        d["_source"] = "template"
        return d
