"""Daily State Intelligence Brief — data builder.

Assembles the full A–I report (+ extras) for a persona's primary state over a 24h
window with 24h-prior deltas. Every section is real, corpus-grounded data; the
narrative prose (exec summary, themed developments, sentiment read, recommended
actions) is generated by one LLM call with a deterministic template fallback.

Universe = articles datelined to the persona's primary state (article_districts),
source_country='IN', last 48h (so we can diff last-24h vs the 24h before).
"""
from __future__ import annotations

import json
import logging
import re
from typing import Any

from sqlalchemy import text

import i18n
from llm_synth import synthesize_paragraph
from map_page import STATE_CODE
from posture import POL, current_mood, principal_of

logger = logging.getLogger("report_builder")

# topic_category -> the six risk domains
DOMAIN_TOPICS = {
    "Political / Social": ["POLITICS", "GOVERNANCE", "SOCIAL"],
    "Law & Order": ["SECURITY", "LEGAL"],
    "Health": ["HEALTH"],
    "Economy": ["BUSINESS", "FINANCE"],
    "Infrastructure": ["INFRASTRUCTURE"],
    "Environment": ["ENVIRONMENT", "AGRICULTURE"],
}
# topic_category -> stakeholder group affected
STAKEHOLDER_TOPICS = {
    "Farmers / rural": ["AGRICULTURE", "ENVIRONMENT"],
    "Public / patients": ["HEALTH"],
    "Industry / business": ["BUSINESS", "FINANCE"],
    "Commuters / residents": ["INFRASTRUCTURE"],
    "Citizens / legal": ["LEGAL", "SECURITY"],
}
STATE_NAMES = {"AP": "Andhra Pradesh", "TG": "Telangana", "KA": "Karnataka", "TN": "Tamil Nadu"}
# A state brief is in the state's own language + English. This drops cross-state
# regional-language stories that the district tagger mis-attributes (e.g. a Tamil
# or Kannada article wrongly tagged to an AP district is NOT Andhra Pradesh news).
STATE_LANG = {"AP": ["te"], "TG": ["te"], "KA": ["kn"], "TN": ["ta"], "KL": ["ml"],
              "MH": ["mr"], "WB": ["bn"], "GJ": ["gu"], "DL": ["hi"], "UP": ["hi"],
              "RJ": ["hi"], "MP": ["hi"], "BR": ["hi"], "OD": ["or"], "PB": ["pa"]}
# Per-state geo_primary markers (lowercased). The universe excludes articles whose
# geo_primary belongs to a state OTHER than the persona's — that's the article-level
# filter that drops cross-state stories an in-state outlet happens to run.
STATE_MARKERS = {
    "AP": {"andhra pradesh", "amaravati", "vijayawada", "visakhapatnam", "vizag", "tirupati", "tirumala",
           "guntur", "nellore", "kurnool", "kadapa", "anantapur", "anantapuram", "rajahmundry", "kakinada",
           "chittoor", "ongole", "eluru", "machilipatnam", "srikakulam", "vizianagaram", "renigunta"},
    "TG": {"telangana", "hyderabad", "secunderabad", "warangal", "nizamabad", "karimnagar", "khammam",
           "mahbubnagar", "mahabubnagar", "nalgonda", "mahabubabad", "peddapalli", "siddipet", "adilabad"},
    "KA": {"karnataka", "bengaluru", "bangalore", "mysuru", "mysore", "hubli", "mangaluru", "belagavi"},
    "KL": {"kerala", "thiruvananthapuram", "kochi", "kozhikode", "thrissur", "kollam", "kannur"},
    "TN": {"tamil nadu", "chennai", "coimbatore", "madurai", "tiruchirappalli", "salem"},
    "MH": {"maharashtra", "mumbai", "pune", "nagpur", "nashik", "thane"},
    "DL": {"delhi", "new delhi"}, "GJ": {"gujarat", "ahmedabad", "surat", "vadodara", "gandhinagar", "rajkot"},
    "WB": {"west bengal", "kolkata"}, "RJ": {"rajasthan", "jaipur", "jodhpur", "udaipur"},
    "UP": {"uttar pradesh", "lucknow", "kanpur", "noida", "varanasi", "prayagraj"},
    "MP": {"madhya pradesh", "bhopal", "indore", "gwalior"}, "BR": {"bihar", "patna"},
    "PB": {"punjab", "chandigarh", "ludhiana", "amritsar"}, "HR": {"haryana", "gurugram", "gurgaon", "faridabad"},
    "OD": {"odisha", "bhubaneswar", "cuttack"},
}
FOREIGN_GEO = {"uk", "usa", "us", "china", "pakistan", "bangladesh", "sri lanka", "nepal",
               "dubai", "london", "washington", "moscow", "russia", "ukraine"}


# Strip URL-slug junk that some sources store as the title: trailing numeric ids,
# ?utm=… query strings, .html suffixes (e.g. "…hydel deal 1961422?utm source=home").
_TITLE_JUNK = re.compile(r"\s*(\d{6,}.*|\?\S.*|\.html?)\s*$", re.I)


def _clean_title(t: str | None) -> str:
    if not t:
        return ""
    c = _TITLE_JUNK.sub("", t.strip()).strip()
    return c or t.strip()


def _primary_state(prefs: dict[str, Any]) -> str:
    for s in (prefs.get("regions") or {}).get("states", []):
        code = STATE_CODE.get((s or "").strip().lower())
        if code:
            return code
    return "AP"


def _severity(n24: int, nprev: int, neg: int) -> str:
    adv = neg / n24 if n24 else 0.0
    vel = n24 / nprev if nprev else (2.0 if n24 else 0.0)
    if n24 >= 20 and adv >= 0.45:
        return "CRITICAL"
    if n24 >= 8 and (adv >= 0.30 or (adv >= 0.18 and vel >= 1.4)):
        return "HIGH"
    if n24 >= 5 and (adv >= 0.10 or vel >= 1.3):
        return "MODERATE"
    return "LOW"


async def _scalar(db, sql: str, p: dict | None = None):
    return (await db.execute(text(sql), p or {})).scalar()


async def build_report(db, prefs: dict[str, Any]) -> dict[str, Any]:
    sc = _primary_state(prefs)
    state_name = STATE_NAMES.get(sc, sc)
    pid, principal = principal_of(prefs)
    N = "analytics.now_sim()"
    # Shared canonical 3-day mood — the ONE directed, intensity-weighted headline
    # mood that Home, War Room and this Report must all show identically. Used for
    # the 'Overall mood' glance card, the Mood section and any mood-driven prose so
    # the whole report is internally consistent (and never contradicts Home/War Room).
    mood = await current_mood(db, pid) if pid else None
    # Block geo_primary markers of every state EXCEPT the persona's, plus foreign.
    block = sorted({m for s, ms in STATE_MARKERS.items() if s != sc for m in ms} | FOREIGN_GEO)

    # Universe = district-tagged to the state AND from an outlet that actually covers
    # the state (sources.geo_states contains the state name). The geo_states filter is
    # what separates Andhra Pradesh from Telangana — both publish in Telugu, so language
    # can't, but Telangana-only outlets (Namasthe/Mana Telangana) lack the state in
    # geo_states. This removes the cross-state stories the district tagger mis-attributes.
    await db.execute(text("DROP TABLE IF EXISTS _rep"))
    await db.execute(text(f"""
        CREATE TEMP TABLE _rep AS
        SELECT DISTINCT a.id, a.topic_category tc, a.collected_at ca, a.title, a.language_iso lang,
               a.url, a.thumbnail_url thumb, a.summary_preview sp, a.geo_primary geo, a.source_id,
               (SELECT avg(({POL}) * st.intensity) FROM article_stances st WHERE st.article_id = a.id) lean
          FROM article_districts ad JOIN districts d ON d.id = ad.district_id
          JOIN articles a ON a.id = ad.article_id
          JOIN sources src ON src.id = a.source_id
         WHERE d.state_code = :sc AND a.source_country = 'IN'
           AND src.geo_states @> ARRAY[:state_full]::text[]
           AND (a.geo_primary IS NULL OR lower(trim(a.geo_primary)) <> ALL(:block))
           AND a.collected_at >= {N} - interval '48 hours'
    """), {"sc": sc, "state_full": state_name, "block": block})
    await db.execute(text("CREATE INDEX ON _rep (ca)"))

    n24 = int(await _scalar(db, f"SELECT count(*) FROM _rep WHERE ca >= {N} - interval '24 hours'") or 0)
    nprev = int(await _scalar(db, f"SELECT count(*) FROM _rep WHERE ca < {N} - interval '24 hours'") or 0)
    now = await _scalar(db, f"SELECT {N}")

    # ── domains / risk heatmap ──
    dom_rows = (await db.execute(text(f"""
        SELECT tc,
               count(*) FILTER (WHERE ca >= {N} - interval '24 hours') n24,
               count(*) FILTER (WHERE ca <  {N} - interval '24 hours') nprev,
               count(*) FILTER (WHERE ca >= {N} - interval '24 hours' AND lean <= -0.1) neg
          FROM _rep WHERE tc IS NOT NULL GROUP BY 1
    """))).fetchall()
    by_topic = {r.tc: {"n24": int(r.n24), "nprev": int(r.nprev), "neg": int(r.neg)} for r in dom_rows}
    domains = []
    for dom, topics in DOMAIN_TOPICS.items():
        a = sum(by_topic.get(t, {}).get("n24", 0) for t in topics)
        b = sum(by_topic.get(t, {}).get("nprev", 0) for t in topics)
        ng = sum(by_topic.get(t, {}).get("neg", 0) for t in topics)
        domains.append({"domain": dom, "n24": a, "nprev": b, "neg": ng,
                        "severity": _severity(a, b, ng),
                        "adverse_pct": round(100 * ng / a) if a else 0,
                        "delta_pct": round(100 * (a - b) / b) if b else 0})
    sev_rank = {"CRITICAL": 0, "HIGH": 1, "MODERATE": 2, "LOW": 3}
    domains.sort(key=lambda d: (sev_rank[d["severity"]], -d["n24"]))

    # ── sentiment: the PRINCIPAL's DIRECTED sentiment (how the press leans TOWARD
    # the desk's subject), not the state-wide undirected coverage tone. Each article
    # mentioning the principal is scored by the AVERAGE of the principal's OWN stance
    # rows (actor_entity_id = the principal = the stance TARGET), so an article that
    # is hostile to the principal reads negative even if its overall tone is mixed. ──
    if pid:
        s = (await db.execute(text(f"""
            WITH pa AS (
              SELECT DISTINCT a.id
                FROM article_entity_mentions m JOIN articles a ON a.id = m.article_id
               WHERE m.entity_id = CAST(:pid AS uuid)
                 AND a.collected_at >= {N} - interval '24 hours'
            )
            SELECT count(*) FILTER (WHERE lean >= 0.1) pos,
                   count(*) FILTER (WHERE lean <= -0.1) neg,
                   count(*) FILTER (WHERE lean > -0.1 AND lean < 0.1) neu,
                   round(100*avg(lean))::int fav
              FROM (
                SELECT pa.id,
                       (SELECT avg(({POL}) * st.intensity) FROM article_stances st
                         WHERE st.article_id = pa.id
                           AND st.actor_entity_id = CAST(:pid AS uuid)) lean
                  FROM pa
              ) x
             WHERE lean IS NOT NULL
        """), {"pid": pid})).fetchone()
    else:
        # Cold-start (no primary subject): fall back to the state-wide undirected tone.
        s = (await db.execute(text(f"""
            SELECT count(*) FILTER (WHERE lean >= 0.1) pos, count(*) FILTER (WHERE lean <= -0.1) neg,
                   count(*) FILTER (WHERE lean > -0.1 AND lean < 0.1) neu,
                   round(100*avg(lean))::int fav
              FROM _rep WHERE ca >= {N} - interval '24 hours'
        """))).fetchone()
    pos, neu, neg = int(s.pos), int(s.neu), int(s.neg)
    scored = pos + neu + neg or 1
    # Net sentiment = the SHARED 3-day directed mood (so the report's headline mood
    # matches Home + War Room exactly). The favourability flips sign by window, so
    # we deliberately use the canonical 3-day value rather than this 24h read. Fall
    # back to the local 24h directed favourability only at cold-start (no principal).
    if mood is not None:
        net_pct = int(mood["fav"])
    else:
        fav = getattr(s, "fav", None)
        net_pct = int(fav) if fav is not None else round(100 * (pos - neg) / scored)

    # ── districts ──
    dd = (await db.execute(text(f"""
        SELECT d.name nm,
               count(DISTINCT a.id) FILTER (WHERE a.collected_at >= {N} - interval '24 hours') n24,
               count(DISTINCT a.id) FILTER (WHERE a.collected_at <  {N} - interval '24 hours') nprev,
               count(DISTINCT a.id) FILTER (WHERE a.collected_at >= {N} - interval '24 hours'
                     AND EXISTS (SELECT 1 FROM article_stances st WHERE st.article_id = a.id AND ({POL}) < 0)) neg
          FROM article_districts ad JOIN districts d ON d.id = ad.district_id JOIN articles a ON a.id = ad.article_id
         WHERE d.state_code = :sc AND a.source_country = 'IN' AND a.collected_at >= {N} - interval '48 hours'
         GROUP BY 1 ORDER BY 2 DESC LIMIT 10
    """), {"sc": sc})).fetchall()
    districts = [{"name": r.nm.title(), "n24": int(r.n24), "nprev": int(r.nprev), "neg": int(r.neg),
                  "delta_pct": round(100 * (int(r.n24) - int(r.nprev)) / int(r.nprev)) if r.nprev else 0}
                 for r in dd]

    # ── top stories: ranked by IMPORTANCE (how many distinct outlets ran the same
    # story, via its lead entity) — not just recency. Thumbnail + recency break ties.
    # We surface the lead entity (the one giving the article its breadth) so the
    # deep-dive block can pull the rest of THAT story's coverage for its Sources line. ──
    ts = (await db.execute(text(f"""
        WITH ent AS (
          SELECT m.entity_id, count(DISTINCT a.source_id) outlets
            FROM article_entity_mentions m JOIN _rep a ON a.id = m.article_id
           WHERE a.ca >= {N} - interval '24 hours' GROUP BY 1
        ), scored AS (
          SELECT DISTINCT ON (m.article_id) m.article_id aid, e.outlets breadth, e.entity_id lead_ent
            FROM article_entity_mentions m JOIN ent e ON e.entity_id = m.entity_id
            JOIN _rep r ON r.id = m.article_id AND r.ca >= {N} - interval '24 hours'
           ORDER BY m.article_id, e.outlets DESC
        )
        SELECT r.id::text aid, r.title, r.lang, s.name src, s.source_tier tier, r.thumb, r.url, r.sp,
               r.geo, r.lean, r.ca, r.tc,
               COALESCE(sc.breadth, 1) breadth, sc.lead_ent::text lead_ent
          FROM _rep r JOIN sources s ON s.id = r.source_id
          LEFT JOIN scored sc ON sc.aid = r.id
         WHERE r.ca >= {N} - interval '24 hours'
         ORDER BY COALESCE(sc.breadth, 1) DESC, (r.thumb IS NOT NULL) DESC, r.ca DESC LIMIT 15
    """))).fetchall()
    top = [{"aid": r.aid, "title": _clean_title(r.title), "lang": r.lang, "source": r.src, "tier": r.tier,
            "thumb": r.thumb, "url": r.url, "summary": (r.sp or "").strip(), "geo": r.geo,
            "breadth": int(r.breadth), "lead_ent": r.lead_ent, "topic": r.tc, "ca": str(r.ca) if r.ca else "",
            "tone": "supportive" if (r.lean or 0) >= 0.1 else "hostile" if (r.lean or 0) <= -0.1 else "neutral"}
           for r in ts]
    await i18n.attach_en(db, top, "title")

    # ── quotes (bilingual) ──
    qs = (await db.execute(text(f"""
        SELECT q.quote_text q, NULLIF(q.quote_text_en,'') qen, COALESCE(q.speaker_name_en, q.speaker_name) who, s.name src
          FROM article_quotes q JOIN _rep r ON r.id = q.article_id JOIN sources s ON s.id = r.source_id
         WHERE r.ca >= {N} - interval '24 hours' AND q.speaker_name IS NOT NULL
           AND length(COALESCE(q.quote_text_en, q.quote_text)) BETWEEN 24 AND 200
         ORDER BY r.ca DESC LIMIT 5
    """))).fetchall()
    quotes = [{"q": r.q, "q_en": (r.qen if (r.qen and r.qen != r.q) else None), "who": r.who or "—", "src": r.src} for r in qs]
    await i18n.attach_en(db, quotes, "q")

    # ── figures ──
    fg = (await db.execute(text(f"""
        SELECT an.value v, an.unit u, an.context c FROM article_numbers an JOIN _rep r ON r.id = an.article_id
         WHERE r.ca >= {N} - interval '24 hours' AND an.unit IS NOT NULL AND length(an.context) BETWEEN 10 AND 120
         ORDER BY r.ca DESC LIMIT 6
    """))).fetchall()
    figures = [{"value": str(r.v), "unit": r.u, "context": r.c} for r in fg]

    # ── source intelligence ──
    tiers = [{"tier": r.tier, "stories": int(r.n), "outlets": int(r.outlets)} for r in (await db.execute(text(f"""
        SELECT s.source_tier tier, count(DISTINCT r.id) n, count(DISTINCT s.id) outlets
          FROM _rep r JOIN sources s ON s.id = r.source_id WHERE r.ca >= {N} - interval '24 hours'
         GROUP BY 1 ORDER BY 1
    """))).fetchall()]
    top_outlets = [{"name": r.nm, "tier": r.tier, "health": round(float(r.h or 0), 2), "n": int(r.n)} for r in (await db.execute(text(f"""
        SELECT s.name nm, s.source_tier tier, s.health_score h, count(DISTINCT r.id) n
          FROM _rep r JOIN sources s ON s.id = r.source_id WHERE r.ca >= {N} - interval '24 hours'
         GROUP BY 1,2,3 ORDER BY 4 DESC LIMIT 6
    """))).fetchall()]

    # ── cross-verification: a "story" (lead entity) covered by >=3 distinct outlets
    # is corroborated; covered by exactly 1 is single-source (treat with caution). ──
    xv = (await db.execute(text(f"""
        WITH ent AS (
          SELECT m.entity_id, count(DISTINCT a.source_id) outlets
            FROM article_entity_mentions m JOIN _rep a ON a.id = m.article_id
           WHERE a.ca >= {N} - interval '24 hours' GROUP BY 1)
        SELECT count(*) FILTER (WHERE outlets >= 3) corroborated,
               count(*) FILTER (WHERE outlets = 1) single FROM ent
    """))).fetchone()
    cross = {"corroborated": int(xv.corroborated or 0), "single_source": int(xv.single or 0)}

    # ── entities / drivers (for stakeholders) ──
    drivers = [{"name": r.nm, "type": r.et, "n": int(r.n)} for r in (await db.execute(text(f"""
        SELECT ed.canonical_name nm, ed.entity_type et, count(DISTINCT m.article_id) n
          FROM article_entity_mentions m JOIN _rep r ON r.id = m.article_id
          JOIN entity_dictionary ed ON ed.id = m.entity_id
         WHERE r.ca >= {N} - interval '24 hours' AND ed.entity_type IN ('person','organization')
         GROUP BY 1,2 ORDER BY 3 DESC LIMIT 8
    """))).fetchall()]
    affected = []
    for grp, topics in STAKEHOLDER_TOPICS.items():
        cnt = sum(by_topic.get(t, {}).get("n24", 0) for t in topics)
        if cnt:
            affected.append({"group": grp, "n": cnt})
    affected.sort(key=lambda x: -x["n"])

    # ── early-warning (rising topics + districts) ──
    early = []
    for t, v in sorted(by_topic.items(), key=lambda x: -(x[1]["n24"])):
        if v["n24"] >= 5 and v["nprev"] and v["n24"] / v["nprev"] >= 1.35:
            early.append({"label": t.title(), "kind": "topic", "now": v["n24"], "prior": v["nprev"],
                          "growth": round(100 * (v["n24"] - v["nprev"]) / v["nprev"])})
    for d in districts:
        if d["n24"] >= 8 and d["nprev"] and d["n24"] / d["nprev"] >= 1.35:
            early.append({"label": d["name"], "kind": "district", "now": d["n24"], "prior": d["nprev"], "growth": d["delta_pct"]})
    early.sort(key=lambda x: -x["growth"])
    early = early[:5]

    # ── deep-dives for the top 3-5 stories (rich grounded prose + every source link) ──
    deep_dives = await _deep_dives(db, top, principal, state_name, N)

    # ── themed development clusters (data; LLM writes the prose) ──
    themes = await _themes(db, sc, N)

    # ── At-a-glance: a plain-language where-it-stands strip (no jargon/formulas) ──
    top_issue = domains[0]["domain"] if domains else "—"
    # Overall mood = the SHARED 3-day directed mood (matches Home + War Room). Note
    # carries the supportive/critical split, the directed subject, and the window so
    # the headline can't be misread. Cold-start (no principal) falls back to the 24h
    # count-based read with its own window label.
    if mood is not None:
        mood_word = mood["word"]
        mood_note = (f"{mood['pos']} supportive vs {mood['neg']} critical · "
                     f"toward {principal} · {mood['window_label']}")
    else:
        mood_word = "broadly positive" if net_pct > 8 else "broadly negative" if net_pct < -8 else "mixed"
        mood_note = f"{pos} supportive vs {neg} critical · last 24 hours"
    at_a_glance = [
        {"label": "Stories today", "value": str(n24),
         "note": f"{'up' if n24 >= nprev else 'down'} from {nprev} the day before"},
        {"label": "Overall mood", "value": mood_word,
         "note": mood_note},
        {"label": "Districts active", "value": str(len(districts)),
         "note": (districts[0]["name"] if districts else "—") + " busiest"},
        {"label": "Top issue", "value": top_issue,
         "note": "the day's most active area of coverage"},
    ]

    structured = {
        "state": state_name, "state_code": sc, "principal": principal,
        "generated_at": str(now), "window_hours": 24,
        "kpis": {"n24": n24, "nprev": nprev, "delta_pct": round(100 * (n24 - nprev) / nprev) if nprev else 0,
                 "net_sentiment": net_pct, "pos": pos, "neu": neu, "neg": neg,
                 "districts_active": len(districts), "adverse_pct": round(100 * neg / scored)},
        "at_a_glance": at_a_glance,
        # Shared 3-day directed mood (matches Home + War Room) — carried so the Mood
        # section and any mood prose label the window + directed subject identically.
        "mood": ({"word": mood["word"], "fav": mood["fav"], "pos": mood["pos"],
                  "neg": mood["neg"], "neu": mood["neu"], "label": mood["label"],
                  "window_label": mood["window_label"], "n": mood["n"]} if mood else None),
        "domains": domains, "sentiment": {"pos": pos, "neu": neu, "neg": neg, "net_pct": net_pct},
        "districts": districts, "top_stories": top, "deep_dives": deep_dives,
        "quotes": quotes, "figures": figures,
        "source_intel": {"tiers": tiers, "top_outlets": top_outlets, "cross": cross},
        "stakeholders": {"affected": affected, "drivers": drivers},
        "early_warning": early, "themes": themes,
        "confidence": "HIGH" if n24 >= 120 else "MODERATE" if n24 >= 40 else "LOW",
    }
    structured["narrative"] = await _narrate(structured)
    structured["narrative"]["exec_paragraph"] = (
        structured["narrative"].get("exec_paragraph") or _exec_paragraph_tpl(structured))
    return structured


# ── Deep-dive prose: a calm political-desk correspondent, never an "AI". ──
_DD_HAPPENED_SYS = (
    "/no_think Respond in English only. You are a seasoned political-desk correspondent writing the "
    "explanatory paragraph that sits under a headline in a serious daily newspaper. Using ONLY the "
    "facts provided (the headline, the outlets that ran it, and any quotes or claims on record), write "
    "ONE flowing paragraph of 4 to 6 sentences telling the reader plainly WHAT HAPPENED and the "
    "immediate context around it. Calm, factual, readable prose for a busy non-technical reader. "
    "Do NOT invent any number, figure, date, place or name that is not in the facts. No bullet points, "
    "no headings, no source citations in brackets, no meta-commentary about being an AI or about the data."
)
_DD_MATTERS_SYS = (
    "/no_think Respond in English only. You are a trusted political adviser briefing your principal in "
    "plain language. Using ONLY the facts provided, write ONE paragraph of 3 to 5 sentences explaining "
    "WHY THIS MATTERS to the principal named in the facts: the significance, who is driving it, and the "
    "concrete risk or the opportunity it opens. Be direct and practical, the way a chief of staff talks. "
    "Do NOT invent any number, figure, date, place or name that is not in the facts. No bullet points, "
    "no headings, no brackets, no mention of being an AI or of underlying data."
)


def _dd_facts(story: dict[str, Any], outlets: list[str], quotes: list[dict[str, Any]],
              claims: list[dict[str, Any]], principal: str, state: str, n_out: int, n_crit: int) -> str:
    """Plain labelled facts for one story — the grounding the correspondent writes from."""
    head = story.get("title_en") or story["title"]
    lines = [f"STATE: {state}. PRINCIPAL (the reader's desk): {principal}.",
             f"HEADLINE: {head}",
             f"LEAD OUTLET: {story.get('source', '')}."]
    if story.get("summary"):
        lines.append(f"STANDFIRST: {story['summary']}")
    if outlets:
        lines.append(f"ALSO RUNNING THIS STORY: {', '.join(outlets[:8])}.")
    lines.append(f"SPREAD: {n_out} outlet(s) carried it; {n_crit} of those pieces were critical in tone.")
    lines.append(f"TONE TOWARD THE SUBJECT: {story.get('tone', 'neutral')}.")
    for q in quotes[:3]:
        who = q.get("who") or "a figure quoted"
        txt = q.get("q_en") or q.get("q") or ""
        if txt:
            lines.append(f"ON RECORD — {who}: \"{txt}\"")
    for c in claims[:3]:
        txt = c.get("text_en") or c.get("text") or ""
        if txt:
            lines.append(f"CLAIM ({c.get('pred', 'claim')}): {txt}")
    return "\n".join(lines)


def _dd_why1_tpl(story: dict[str, Any], n_out: int) -> str:
    """One-line 'why this matters to you' teaser that sits under the headline."""
    tone = story.get("tone", "neutral")
    if n_out >= 4:
        reach = "It is one of the most widely-carried stories on your desk today"
    elif n_out > 1:
        reach = "It is being carried by several outlets at once"
    else:
        reach = "It is an early-stage story worth watching before it spreads"
    angle = {"hostile": "and the framing is running against you",
             "supportive": "and the framing is currently in your favour"}.get(
        tone, "and the framing has not yet settled")
    return f"{reach} {angle}."


def _dd_happened_tpl(story: dict[str, Any], outlets: list[str], n_out: int, n_crit: int,
                     quotes: list[dict[str, Any]], claims: list[dict[str, Any]],
                     numbers: list[dict[str, Any]]) -> str:
    """A complete, journalist-voice 'what happened' narrative built only from this
    story's own facts — headline, breadth, standfirst, a quote, a claim, a figure."""
    head = (story.get("title_en") or story["title"]).rstrip(".")
    src = story.get("source") or "a state outlet"
    s = [f"{head}, first carried by {src}."]
    if story.get("summary"):
        sm = story["summary"].replace("\n", " ").strip().rstrip(".")
        if sm:
            s.append(sm + ".")
    if n_out > 1:
        also = (", among them " + ", ".join(outlets[:4])) if len(outlets) > 1 else ""
        s.append(f"The same story has been picked up across {n_out} outlets in the state{also}, "
                 f"which puts it among the day's more widely-run items.")
    else:
        s.append("For now it sits with a single outlet, so it is worth watching to see whether "
                 "the rest of the press follows.")
    q0 = next((q for q in quotes if (q.get("q_en") or q.get("q"))), None)
    if q0:
        qt = (q0.get("q_en") or q0.get("q") or "").strip().strip('"')
        who = q0.get("who") or "one of those quoted"
        s.append(f"On the record, {who} said: “{qt}”")
    c0 = next((c for c in claims if (c.get("text_en") or c.get("text"))), None)
    if c0:
        ct = (c0.get("text_en") or c0.get("text") or "").strip().rstrip(".")
        if ct:
            s.append(f"Among the specifics being reported: {ct}.")
    f0 = numbers[0] if numbers else None
    if f0 and f0.get("context"):
        s.append(f"One figure running through the coverage is {f0.get('value','')} "
                 f"{f0.get('unit','')} — {f0['context'].rstrip('.')}.")
    if n_crit and (story.get("tone") == "hostile" or n_crit >= 2):
        s.append(f"The tone has run critical in {n_crit} of those pieces, which will shape how "
                 "the story is read over the next news cycle.")
    elif story.get("tone") == "supportive":
        s.append("The coverage has been broadly favourable in tone so far.")
    else:
        s.append("The reporting has been largely straight in tone to this point.")
    # Trim to ~4-5 sentences so the block fits one page; readability over length.
    sentences = [x for x in s if x]
    return " ".join(sentences[:5]).strip()


def _dd_matters_tpl(story: dict[str, Any], principal: str, drivers: list[str],
                    n_out: int, n_crit: int) -> str:
    """A complete 3-5 sentence diagnosis: significance, who is driving it, the
    risk or opportunity, and the practical next move — chief-of-staff voice."""
    tone = story.get("tone", "neutral")
    s = [f"For the {principal} desk, the signal here is reach rather than any single line: "
         f"{n_out} outlet{'s' if n_out != 1 else ''} carrying the same story means it is "
         "helping to set the day's agenda whether or not it is answered."]
    if drivers:
        who = ", ".join(drivers[:3])
        s.append(f"The figures driving the coverage are {who}, so any response is best aimed "
                 "at the frame they are setting rather than at the outlets alone.")
    if tone == "hostile" or n_crit:
        s.append("Because the tone is largely adverse, the near-term risk is that the criticism "
                 "hardens into the accepted version of events before a counter-account is on record.")
        s.append("The practical move is to decide quickly whether to contest it through a "
                 "friendly outlet now or let it run its course.")
    elif tone == "supportive":
        s.append("The tone is favourable, so the opportunity is to amplify it while it is still "
                 "fresh and travelling, and to tie it to the wider message of the week.")
        s.append("The risk is only that a single supportive cycle is mistaken for a settled "
                 "narrative; it should be reinforced, not assumed.")
    else:
        s.append("The tone is neutral for now, which leaves room to shape how the story is "
                 "understood before a frame sets and becomes costly to move.")
        s.append("The practical move is to get ahead of it with a clear line while the coverage "
                 "is still open.")
    # Trim to ~3-4 sentences so the block fits one page; substantive but not maximal.
    return " ".join(s[:4]).strip()


def _story_sig(story: dict[str, Any]) -> str:
    """A coarse de-dupe key for a story so we don't deep-dive the same event twice,
    WITHOUT collapsing every political story onto one shared lead entity. Built from
    the first few significant words of the (English) headline."""
    head = (story.get("title_en") or story.get("title") or "").lower()
    words = re.findall(r"[a-z0-9]{4,}", head)
    return " ".join(words[:5])


async def _deep_dives(db, top: list[dict[str, Any]], principal: str, state: str,
                      N: str) -> list[dict[str, Any]]:
    """The 5-6 biggest stories, each a COMPLETE block: a rich grounded narrative, a
    diagnosis, who is driving it, verbatim quotes, the numbers, and EVERY source
    article that ran the story. The LLM is an optional enhancement only — the
    multi-sentence template is itself complete and grounded in the story's own facts."""
    TARGET = 6
    out: list[dict[str, Any]] = []
    seen_sig: set[str] = set()
    for story in top:
        if len(out) >= TARGET:
            break
        # De-dupe on a HEADLINE signature, not the lead entity: high-breadth political
        # stories nearly all share one dominant lead entity (the ruling figure/party),
        # so an entity-keyed dedup collapsed the whole list onto a single deep-dive.
        sig = _story_sig(story)
        if sig and sig in seen_sig:
            continue
        if sig:
            seen_sig.add(sig)
        lead = story.get("lead_ent")

        outlets: list[str] = []
        sources: list[dict[str, Any]] = []
        n_out, n_crit = 1, 0
        if lead:
            # Every article in the window whose lead/any entity is this story's lead
            # entity = the full footprint of this story. These are the Sources links.
            srows = (await db.execute(text(f"""
                SELECT DISTINCT r.url, s.name src, s.source_tier tier, r.title,
                       (r.lean <= -0.1) crit
                  FROM article_entity_mentions m
                  JOIN _rep r ON r.id = m.article_id AND r.ca >= {N} - interval '24 hours'
                  JOIN sources s ON s.id = r.source_id
                 WHERE m.entity_id = CAST(:eid AS uuid)
                 ORDER BY s.source_tier NULLS LAST, s.name
            """), {"eid": lead})).fetchall()
            seen_url: set[str] = set()
            for sr in srows:
                if sr.url and sr.url in seen_url:
                    continue
                if sr.url:
                    seen_url.add(sr.url)
                sources.append({"url": sr.url, "outlet": sr.src, "tier": sr.tier})
                if sr.src and sr.src not in outlets:
                    outlets.append(sr.src)
                if sr.crit:
                    n_crit += 1
            n_out = len(outlets) or 1
        if not sources and story.get("url"):
            sources = [{"url": story["url"], "outlet": story.get("source"), "tier": story.get("tier")}]
            outlets = [story.get("source")] if story.get("source") else []
        # n_out is the breadth of THIS story; fall back to the story's own breadth count.
        n_out = max(n_out, int(story.get("breadth", 1) or 1))

        # Grounding material: quotes + claims + numbers attached to this story's articles.
        quotes: list[dict[str, Any]] = []
        claims: list[dict[str, Any]] = []
        numbers: list[dict[str, Any]] = []
        drivers: list[str] = []
        if lead:
            qrows = (await db.execute(text(f"""
                SELECT q.quote_text q, NULLIF(q.quote_text_en,'') qen,
                       COALESCE(q.speaker_name_en, q.speaker_name) who, s.name src
                  FROM article_quotes q
                  JOIN article_entity_mentions m ON m.article_id = q.article_id
                  JOIN _rep r ON r.id = q.article_id AND r.ca >= {N} - interval '24 hours'
                  JOIN sources s ON s.id = r.source_id
                 WHERE m.entity_id = CAST(:eid AS uuid) AND q.speaker_name IS NOT NULL
                   AND length(COALESCE(q.quote_text_en, q.quote_text)) BETWEEN 24 AND 220
                 ORDER BY r.ca DESC LIMIT 4
            """), {"eid": lead})).fetchall()
            quotes = [{"q": r.q, "q_en": (r.qen if (r.qen and r.qen != r.q) else None),
                       "who": r.who, "src": r.src} for r in qrows]
            await i18n.attach_en(db, quotes, "q")
            crows = (await db.execute(text(f"""
                SELECT c.predicate pred, COALESCE(c.object_text, c.claim_text) txt
                  FROM article_claims c
                  JOIN article_entity_mentions m ON m.article_id = c.article_id
                  JOIN _rep r ON r.id = c.article_id AND r.ca >= {N} - interval '24 hours'
                 WHERE m.entity_id = CAST(:eid AS uuid)
                   AND COALESCE(c.object_text, c.claim_text) IS NOT NULL
                   AND length(COALESCE(c.object_text, c.claim_text)) BETWEEN 12 AND 200
                 ORDER BY r.ca DESC LIMIT 3
            """), {"eid": lead})).fetchall()
            claims = [{"pred": (r.pred or "claim"), "text": (r.txt or "").strip()} for r in crows]
            await i18n.attach_en(db, claims, "text")
            nrows = (await db.execute(text(f"""
                SELECT an.value v, an.unit u, an.context c
                  FROM article_numbers an
                  JOIN article_entity_mentions m ON m.article_id = an.article_id
                  JOIN _rep r ON r.id = an.article_id AND r.ca >= {N} - interval '24 hours'
                 WHERE m.entity_id = CAST(:eid AS uuid) AND an.unit IS NOT NULL
                   AND length(an.context) BETWEEN 10 AND 120
                 ORDER BY r.ca DESC LIMIT 4
            """), {"eid": lead})).fetchall()
            numbers = [{"value": str(r.v), "unit": r.u, "context": (r.c or "").strip()} for r in nrows]
            drows = (await db.execute(text(f"""
                SELECT ed.canonical_name nm, count(DISTINCT m2.article_id) n
                  FROM article_entity_mentions m
                  JOIN _rep r ON r.id = m.article_id AND r.ca >= {N} - interval '24 hours'
                  JOIN article_entity_mentions m2 ON m2.article_id = m.article_id
                  JOIN entity_dictionary ed ON ed.id = m2.entity_id
                 WHERE m.entity_id = CAST(:eid AS uuid)
                   AND ed.entity_type IN ('person','organization')
                 GROUP BY 1 ORDER BY 2 DESC LIMIT 4
            """), {"eid": lead})).fetchall()
            drivers = [r.nm for r in drows if r.nm]

        facts = _dd_facts(story, outlets, quotes, claims, principal, state, n_out, n_crit)
        # source_check = the real headlines/standfirst/quotes — what the numeric gate
        # validates the prose against. Story metrics (n_out/n_crit) live here too so a
        # faithful "3 outlets" line passes.
        check = facts + f"\n{n_out} {n_crit} 24"

        # LLM is OPTIONAL enhancement; the template fallback is complete on its own.
        happened = await synthesize_paragraph(
            system=_DD_HAPPENED_SYS, facts=facts, source_check=check, min_words=40, min_chars=200)
        matters = await synthesize_paragraph(
            system=_DD_MATTERS_SYS, facts=facts, source_check=check, min_words=24, min_chars=120)

        out.append({
            "thumb": story.get("thumb"),
            "headline": story.get("title", ""),
            "headline_en": story.get("title_en"),
            "tone": story.get("tone", "neutral"),
            "topic": (story.get("topic") or "").title(),
            "breadth": n_out,
            "why1": _dd_why1_tpl(story, n_out),
            "drivers": drivers,
            # n_crit is counted from UNDIRECTED article lean (overall adverse tone),
            # NOT pieces critical OF the principal — so label it 'adverse' to stay honest.
            "metric_line": (f"{n_out} outlet{'s' if n_out != 1 else ''} · "
                            f"{n_crit} adverse piece{'s' if n_crit != 1 else ''} · last 24h"),
            "happened": happened or _dd_happened_tpl(story, outlets, n_out, n_crit, quotes, claims, numbers),
            "matters": matters or _dd_matters_tpl(story, principal, drivers, n_out, n_crit),
            "quotes": [q for q in quotes if (q.get("q_en") or q.get("q"))][:2],
            "numbers": numbers[:3],
            # Cap sources so a deep dive fits one page (compact inline list of ~18).
            "sources": sources[:18],
        })
    return out


async def _themes(db, sc: str, N: str) -> list[dict[str, Any]]:
    """Top representative stories per theme (keyword/topic), for the LLM to write up."""
    THEME_DEFS = [
        ("Party & political friction", "tc IN ('POLITICS') AND lean <= -0.05"),
        ("Governance & policy", "tc IN ('GOVERNANCE') OR title ~* '(scheme|cabinet|policy|project|launch|sanction|grant)'"),
        ("Courts & law", "tc IN ('LEGAL') OR title ~* '(court|verdict|bail|petition|case|arrest|probe)'"),
        ("Crime & security", "tc IN ('SECURITY') OR title ~* '(murder|attack|police|seized|smuggl|assault)'"),
        ("Economy & markets", "tc IN ('BUSINESS','FINANCE')"),
        ("Environment & natural", "tc IN ('ENVIRONMENT','AGRICULTURE') OR title ~* '(rain|flood|heat|cyclone|drought|crop)'"),
    ]
    out = []
    for label, cond in THEME_DEFS:
        rows = (await db.execute(text(f"""
            SELECT r.title, s.name src, r.sp, r.geo, r.lean
              FROM _rep r JOIN sources s ON s.id = r.source_id
             WHERE r.ca >= {N} - interval '24 hours' AND ({cond})
             ORDER BY r.ca DESC LIMIT 4
        """))).fetchall()
        if len(rows) >= 2:
            items = [{"title": _clean_title(r.title), "src": r.src, "summary": (r.sp or "").strip(), "geo": r.geo} for r in rows]
            await i18n.attach_en(db, items, "title")
            out.append({"theme": label, "count": len(rows), "items": items})
    return out[:4]


def _facts_blob(s: dict[str, Any]) -> str:
    md = s.get("mood")
    sent_line = (f"SENTIMENT (mood directed toward {s['principal']}, {md['window_label']}): "
                 f"{md['word']} (net {s['sentiment']['net_pct']:+d}%); "
                 f"{md['pos']} supportive / {md['neu']} neutral / {md['neg']} critical pieces toward them."
                 if md else
                 f"SENTIMENT: {s['sentiment']['pos']} supportive / {s['sentiment']['neu']} neutral / "
                 f"{s['sentiment']['neg']} critical (net {s['sentiment']['net_pct']:+d}%).")
    lines = [f"STATE: {s['state']} (principal desk: {s['principal']})",
             f"VOLUME: {s['kpis']['n24']} stories in 24h vs {s['kpis']['nprev']} prior ({s['kpis']['delta_pct']:+d}%).",
             sent_line]
    lines.append("RISK DOMAINS: " + "; ".join(f"{d['domain']}={d['severity']} ({d['n24']} stories, {d['adverse_pct']}% adverse, {d['delta_pct']:+d}% vs prior)" for d in s["domains"]))
    lines.append("TOP DISTRICTS: " + ", ".join(f"{d['name']} {d['n24']}({d['delta_pct']:+d}%)" for d in s["districts"][:6]))
    if s["early_warning"]:
        lines.append("RISING: " + ", ".join(f"{e['label']} {e['prior']}->{e['now']} (+{e['growth']}%)" for e in s["early_warning"]))
    for th in s["themes"]:
        heads = " | ".join((it.get("title_en") or it["title"]) + (f" — {it['summary']}" if it.get("summary") else "") for it in th["items"][:3])
        lines.append(f"THEME [{th['theme']}]: {heads}")
    if s["figures"]:
        lines.append("FIGURES: " + "; ".join(f"{f['value']} {f['unit']} ({f['context']})" for f in s["figures"][:5]))
    return "\n".join(lines)


_SYS = (
    "You are a senior intelligence analyst writing a confidential daily brief for the desk named at "
    "the top of the FACTS. Write in crisp, authoritative, knowledge-rich prose (Stratfor / BBC-"
    "Monitoring voice). Be specific and interpretive: what happened, why it matters to the state, and "
    "the second-order risk or opportunity.\n"
    "HARD RULES (failure to follow makes the brief unusable):\n"
    "1. ONLY write about the state named in the FACTS. If a fact is about another state (e.g. Telangana, "
    "Karnataka, Kerala) or a national/foreign matter, IGNORE it — never build a development or summary "
    "around it.\n"
    "2. NEVER state a number, percentage, count, rank, share or amount that is not explicitly present in "
    "the FACTS. Do not estimate, extrapolate, or invent statistics (e.g. never write 'X% of stories').\n"
    "3. Do NOT merge unrelated stories into one theme or invent a connecting thesis. If a theme's items "
    "are different unrelated events, write about the single most significant one and omit the rest.\n"
    "4. No citations, no source names in brackets, no hedging boilerplate.\n\n"
    "Return ONLY valid JSON with this exact shape:\n"
    "{\n"
    '  "exec_paragraph": "<3-4 plain-language sentences summarising the whole day for a busy non-technical reader: how active the press was, the overall tone, and the single biggest story — no numbers beyond those in the FACTS, no jargon>",\n'
    '  "exec_summary": [ "<6-7 punchy bullets, each one rich sentence, on what changed in 24h and why it matters>" ],\n'
    '  "hotspot_read": "<2-3 sentences interpreting the district geography>",\n'
    '  "sentiment_narrative": "<3-4 sentences on tone, polarisation, and any narrative divergence>",\n'
    '  "developments": [ {"theme": "<theme>", "headline": "<rewritten sharp headline>", "body": "<3-4 detailed sentences contextualising the cluster>"} ],\n'
    '  "actions": [ "<5 concrete, prioritised recommended actions tied to the signals>" ]\n'
    "}\n"
    "Make developments cover the themes provided. Make it genuinely useful, not generic."
)


def _exec_paragraph_tpl(s: dict[str, Any]) -> str:
    """A plain-language 3-4 sentence executive summary of the day — no jargon, no
    formulas. Reads like the opening of a real morning brief, grounded in the data."""
    k = s["kpis"]
    state = s["state"]
    n24, nprev = k["n24"], k["nprev"]
    moved = "busier than" if n24 > nprev else "quieter than" if n24 < nprev else "in line with"
    net = k["net_sentiment"]
    if net > 8:
        mood = "and the overall tone leaned in your favour"
    elif net < -8:
        mood = "and the overall tone ran against you"
    else:
        mood = "and the tone was mixed, with no clear lean either way"
    lead = ""
    deep = s.get("deep_dives") or []
    if deep:
        h = (deep[0].get("headline_en") or deep[0].get("headline") or "").rstrip(".")
        if h:
            lead = f" The story leading the desk today is {h}."
    dom = s["domains"][0]["domain"] if s["domains"] else "general affairs"
    dists = s["districts"]
    where = (f" Coverage was heaviest around {dists[0]['name']}"
             + (f" and {dists[1]['name']}" if len(dists) > 1 else "") + ".") if dists else ""
    return (f"Across {state} the press ran {n24} stories in the last 24 hours, {moved} the "
            f"{nprev} of the day before, {mood}.{lead} The most active area of coverage was "
            f"{dom.lower()}.{where}").strip()


def _templates(s: dict[str, Any]) -> dict[str, Any]:
    """Deterministic fallback if the LLM is unavailable."""
    k = s["kpis"]
    top_dom = s["domains"][0]
    exec_s = [
        f"Coverage {('rose' if k['delta_pct'] > 0 else 'cooled')} {abs(k['delta_pct'])}% ({k['n24']} vs {k['nprev']} stories) over the last 24 hours.",
        f"Net sentiment is {k['net_sentiment']:+d}% — {s['sentiment']['pos']} supportive against {s['sentiment']['neg']} critical pieces.",
        f"{top_dom['domain']} is the day's hottest domain ({top_dom['severity']}, {top_dom['adverse_pct']}% adverse).",
    ]
    if s["districts"]:
        d0 = s["districts"][0]
        exec_s.append(f"{d0['name']} leads district coverage with {d0['n24']} stories.")
    for e in s["early_warning"][:2]:
        exec_s.append(f"{e['label']} is rising fast — {e['prior']}→{e['now']} ({e['growth']:+d}%).")
    devs = [{"theme": t["theme"], "headline": (t["items"][0].get("title_en") or t["items"][0]["title"]),
             "body": " ".join(it.get("summary") or "" for it in t["items"][:2]).strip() or "Multiple stories in this theme this window."}
            for t in s["themes"]]
    actions = [f"Monitor {top_dom['domain']} — the highest-adverse domain today."]
    for e in s["early_warning"][:2]:
        actions.append(f"Track the {e['label']} surge (+{e['growth']}%) over the next 48 hours.")
    actions.append("Hold on low-severity domains; preserve attention for the amber board.")
    return {"exec_paragraph": _exec_paragraph_tpl(s),
            "exec_summary": exec_s, "hotspot_read": "Coverage concentrates in the busiest districts; watch the fastest risers.",
            "sentiment_narrative": f"Tone is net {k['net_sentiment']:+d}%, with negativity concentrated in the higher-severity domains.",
            "developments": devs, "actions": actions}


async def _narrate(s: dict[str, Any]) -> dict[str, Any]:
    try:
        from groq_client import generate
        raw = await generate(system=_SYS, user=_facts_blob(s), task_type="brief_generation")
        txt = raw.strip()
        i, j = txt.find("{"), txt.rfind("}")
        data = json.loads(txt[i:j + 1])
        if not data.get("exec_summary"):
            raise ValueError("empty exec_summary")
        # backfill any missing keys from templates
        tpl = _templates(s)
        for key in ("exec_paragraph", "exec_summary", "hotspot_read", "sentiment_narrative", "developments", "actions"):
            if not data.get(key):
                data[key] = tpl[key]
        data["_source"] = "llm"
        return data
    except Exception as exc:  # noqa: BLE001 — degrade to templates, never fail the report
        logger.warning("report narrate: LLM unavailable (%s); using templates", exc)
        d = _templates(s)
        d["_source"] = "template"
        return d
