\set ON_ERROR_STOP on
BEGIN;
INSERT INTO entity_dictionary (id,canonical_name,entity_type,aliases,country,source) VALUES
('11c78c78-cbee-42b7-939c-ccc16b955e7c','Antigua and Barbuda','location',ARRAY['Antigua and Barbuda','Antigua'],'AG','seed:commonwealth_v1'),
('8974ebca-cb2c-4c5a-958d-4ce9793166e6','Bahamas','location',ARRAY['Bahamas','The Bahamas'],'BS','seed:commonwealth_v1'),
('716dbac7-095e-4823-b74d-771b00d88ce7','Barbados','location',ARRAY['Barbados'],'BB','seed:commonwealth_v1'),
('e9e3f120-8d8d-480d-a8d3-387a063164a4','Belize','location',ARRAY['Belize'],'BZ','seed:commonwealth_v1'),
('f4a42fd6-399d-45c6-a217-5083a0bffdb9','Botswana','location',ARRAY['Botswana','Republic of Botswana'],'BW','seed:commonwealth_v1'),
('dbdaf5cc-f5e5-48c1-ad34-fed44fcbcbd7','Brunei','location',ARRAY['Brunei','Brunei Darussalam'],'BN','seed:commonwealth_v1'),
('1877122c-8c55-495c-8690-3c308ba03ca4','Dominica','location',ARRAY['Dominica','Commonwealth of Dominica'],'DM','seed:commonwealth_v1'),
('b063eaba-81af-4790-9710-bd810578390e','Fiji','location',ARRAY['Fiji','Republic of Fiji'],'FJ','seed:commonwealth_v1'),
('6a539821-0499-4ae0-bd44-dd7e2c3da5d8','Gabon','location',ARRAY['Gabon','Gabonese Republic'],'GA','seed:commonwealth_v1'),
('6ae264d5-9432-49fa-aedc-a0d59715903f','Gambia','location',ARRAY['Gambia','The Gambia'],'GM','seed:commonwealth_v1'),
('a633f720-e4d9-46a2-94dd-00295940f692','Grenada','location',ARRAY['Grenada'],'GD','seed:commonwealth_v1'),
('88705836-5a19-49eb-ada1-0fcf78bbd64c','Guyana','location',ARRAY['Guyana'],'GY','seed:commonwealth_v1'),
('c32cc207-d4de-4a43-a358-93b2f538cf8a','Kiribati','location',ARRAY['Kiribati'],'KI','seed:commonwealth_v1'),
('79767672-6903-4ed7-9805-2380b1d4f0f7','Lesotho','location',ARRAY['Lesotho','Kingdom of Lesotho'],'LS','seed:commonwealth_v1'),
('e9aed0a5-933c-4c61-b6b3-134f175234f7','Maldives','location',ARRAY['Maldives','Republic of Maldives'],'MV','seed:commonwealth_v1'),
('0c24c709-4336-4d04-a947-0157f2e771a3','Malta','location',ARRAY['Malta','Republic of Malta'],'MT','seed:commonwealth_v1'),
('0fba5b5d-f203-48d2-9e8c-444b3912ee0a','Mauritius','location',ARRAY['Mauritius','Republic of Mauritius'],'MU','seed:commonwealth_v1'),
('5fe34b08-c4f9-4017-90d8-f4c4da59a3bd','Nauru','location',ARRAY['Nauru','Republic of Nauru'],'NR','seed:commonwealth_v1'),
('07d0b0a1-f2c1-4d71-8aa3-973ae5735d36','Saint Kitts and Nevis','location',ARRAY['Saint Kitts and Nevis','St Kitts and Nevis','St. Kitts and Nevis','Saint Kitts'],'KN','seed:commonwealth_v1'),
('a1c74dd6-4b8b-48cc-a8cb-15a086c59b24','Saint Lucia','location',ARRAY['Saint Lucia','St Lucia','St. Lucia'],'LC','seed:commonwealth_v1'),
('71e6a03d-3881-4600-9061-1005f1d2148c','Saint Vincent and the Grenadines','location',ARRAY['Saint Vincent and the Grenadines','St Vincent and the Grenadines','Saint Vincent'],'VC','seed:commonwealth_v1'),
('0dfae17e-d1bb-407a-a928-c91afc04541b','Samoa','location',ARRAY['Samoa'],'WS','seed:commonwealth_v1'),
('8d08551e-de7c-47e4-b988-5619e987a502','Seychelles','location',ARRAY['Seychelles','Republic of Seychelles'],'SC','seed:commonwealth_v1'),
('1136d498-76d6-45e2-9871-54307b9bc724','Solomon Islands','location',ARRAY['Solomon Islands'],'SB','seed:commonwealth_v1'),
('7808ffce-0cf4-42fe-9a67-f4ba2eaf041c','Tonga','location',ARRAY['Tonga','Kingdom of Tonga'],'TO','seed:commonwealth_v1'),
('58b0e759-cdcb-426a-afec-d62955aba6d2','Trinidad and Tobago','location',ARRAY['Trinidad and Tobago','Trinidad'],'TT','seed:commonwealth_v1'),
('bdee6816-83da-478e-bd35-5df800f0842c','Tuvalu','location',ARRAY['Tuvalu'],'TV','seed:commonwealth_v1')
ON CONFLICT (canonical_name) DO NOTHING;

INSERT INTO entity_lookup (name_norm, entity_id)
SELECT lower(v.alias), ed.id FROM (VALUES
('Antigua and Barbuda','Antigua and Barbuda'),
('Antigua and Barbuda','Antigua'),
('Bahamas','Bahamas'),
('Bahamas','The Bahamas'),
('Barbados','Barbados'),
('Belize','Belize'),
('Botswana','Botswana'),
('Botswana','Republic of Botswana'),
('Brunei','Brunei'),
('Brunei','Brunei Darussalam'),
('Dominica','Dominica'),
('Dominica','Commonwealth of Dominica'),
('Fiji','Fiji'),
('Fiji','Republic of Fiji'),
('Gabon','Gabon'),
('Gabon','Gabonese Republic'),
('Gambia','Gambia'),
('Gambia','The Gambia'),
('Grenada','Grenada'),
('Guyana','Guyana'),
('Kiribati','Kiribati'),
('Lesotho','Lesotho'),
('Lesotho','Kingdom of Lesotho'),
('Maldives','Maldives'),
('Maldives','Republic of Maldives'),
('Malta','Malta'),
('Malta','Republic of Malta'),
('Mauritius','Mauritius'),
('Mauritius','Republic of Mauritius'),
('Nauru','Nauru'),
('Nauru','Republic of Nauru'),
('Saint Kitts and Nevis','Saint Kitts and Nevis'),
('Saint Kitts and Nevis','St Kitts and Nevis'),
('Saint Kitts and Nevis','St. Kitts and Nevis'),
('Saint Kitts and Nevis','Saint Kitts'),
('Saint Lucia','Saint Lucia'),
('Saint Lucia','St Lucia'),
('Saint Lucia','St. Lucia'),
('Saint Vincent and the Grenadines','Saint Vincent and the Grenadines'),
('Saint Vincent and the Grenadines','St Vincent and the Grenadines'),
('Saint Vincent and the Grenadines','Saint Vincent'),
('Samoa','Samoa'),
('Seychelles','Seychelles'),
('Seychelles','Republic of Seychelles'),
('Solomon Islands','Solomon Islands'),
('Tonga','Tonga'),
('Tonga','Kingdom of Tonga'),
('Trinidad and Tobago','Trinidad and Tobago'),
('Trinidad and Tobago','Trinidad'),
('Tuvalu','Tuvalu')
) v(canonical,alias) JOIN entity_dictionary ed ON ed.canonical_name=v.canonical
ON CONFLICT (name_norm) DO NOTHING;
COMMIT;

\echo '### verify: dict rows added + how many of the 27 now resolve in entity_lookup'
SELECT count(*) commonwealth_dict_rows FROM entity_dictionary WHERE source='seed:commonwealth_v1';
WITH n(nm) AS (VALUES ('antigua and barbuda'),('bahamas'),('barbados'),('belize'),('botswana'),('brunei'),('dominica'),('fiji'),('gabon'),('gambia'),('grenada'),('guyana'),('kiribati'),('lesotho'),('maldives'),('malta'),('mauritius'),('nauru'),('saint kitts and nevis'),('saint lucia'),('saint vincent and the grenadines'),('samoa'),('seychelles'),('solomon islands'),('tonga'),('trinidad and tobago'),('tuvalu')) SELECT count(*) total, count(*) FILTER (WHERE EXISTS(SELECT 1 FROM entity_lookup el WHERE el.name_norm=n.nm)) resolves FROM n;
