\set ON_ERROR_STOP on
BEGIN;
SELECT count(*) AS before_total FROM sources;
INSERT INTO sources (name,domain,rss_url,source_type,source_tier,language,country,topics,is_active) VALUES
('Antigua News Room','antiguanewsroom.com','https://antiguanewsroom.com','rss',1,'en','AG',ARRAY['national_flagship'],false),
('ZNS Bahamas','znsbahamas.com','https://znsbahamas.com','rss',2,'en','BS',ARRAY['national_flagship'],false),
('Our News Bahamas','ournews.bs','https://ournews.bs','rss',2,'en','BS',ARRAY['national_flagship'],false),
('Bahamas Press','bahamaspress.com','https://bahamaspress.com','rss',2,'en','BS',ARRAY['national_flagship'],false),
('CBC Barbados','cbc.bb','https://cbc.bb','rss',2,'en','BB',ARRAY['national_flagship'],false),
('Nation News Barbados','nationnews.com','https://nationnews.com','rss',1,'en','BB',ARRAY['national_flagship'],false),
('Channel 5 Belize','edition.channel5belize.com','https://edition.channel5belize.com','rss',1,'en','BZ',ARRAY['national_flagship'],false),
('Belize Press','belizepress.com','https://belizepress.com','rss',3,'en','BZ',ARRAY['national_flagship'],false),
('Amandala Belize','amandala.com.bz','https://amandala.com.bz','rss',1,'en','BZ',ARRAY['national_flagship'],false),
('The Reporter Belize','reporter.bz','https://reporter.bz','rss',1,'en','BZ',ARRAY['national_flagship'],false),
('Channel 7 Belize','7newsbelize.com','https://7newsbelize.com','rss',1,'en','BZ',ARRAY['national_flagship'],false),
('Weekend Post','weekendpost.co.bw','https://weekendpost.co.bw','rss',2,'en','BW',ARRAY['national_flagship'],false),
('The Voice Botswana','thevoicebw.com','https://thevoicebw.com','rss',2,'en','BW',ARRAY['national_flagship'],false),
('Sunday Standard','sundaystandard.info','https://sundaystandard.info','rss',1,'en','BW',ARRAY['national_flagship'],false),
('Mmegi Online','mmegi.bw','https://mmegi.bw','rss',1,'en','BW',ARRAY['national_flagship'],false),
('Brunei Press','bruneipress.com.bn','https://bruneipress.com.bn','rss',2,'en','BN',ARRAY['english_language'],false),
('Brudirect','brudirect.com','https://brudirect.com','rss',2,'en','BN',ARRAY['national_flagship'],false),
('The Scoop Brunei','thescoop.co','https://thescoop.co','rss',1,'en','BN',ARRAY['investigative'],false),
('The Brunei Times','bt.com.bn','https://bt.com.bn','rss',3,'en','BN',ARRAY['english_language'],false),
('Cyprus Mail','cyprus-mail.com','https://cyprus-mail.com','rss',1,'en','CY',ARRAY['english_language'],false),
('Haravgi','haravgi.com.cy','https://haravgi.com.cy','rss',3,'el','CY',ARRAY['political'],false),
('Yeni Bakis','yenibakis.com','https://yenibakis.com','rss',3,'tr','CY',ARRAY['vernacular_turkish'],false),
('Politis','politis.com.cy','https://politis.com.cy','rss',1,'el','CY',ARRAY['national_flagship'],false),
('Yeni Duzen','yeniduzen.com','https://yeniduzen.com','rss',2,'tr','CY',ARRAY['vernacular_turkish'],false),
('Sigmalive','sigmalive.com','https://sigmalive.com','rss',1,'el','CY',ARRAY['national_flagship'],false),
('Alithia','alithia.com.cy','https://alithia.com.cy','rss',2,'el','CY',ARRAY['national_flagship'],false),
('Reporter CY','reporter.com.cy','https://reporter.com.cy','rss',2,'el','CY',ARRAY['national_flagship'],false),
('Kathimerini Cyprus','kathimerini.com.cy','https://kathimerini.com.cy','rss',1,'el','CY',ARRAY['national_flagship'],false),
('Stockwatch','stockwatch.com.cy','https://stockwatch.com.cy','rss',2,'en','CY',ARRAY['financial'],false),
('In Cyprus','in-cyprus.philenews.com','https://in-cyprus.philenews.com','rss',2,'en','CY',ARRAY['english_language'],false),
('Famagusta Gazette','famagusta-gazette.com','https://famagusta-gazette.com','rss',2,'en','CY',ARRAY['english_language'],false),
('Phileleftheros','philenews.com','https://philenews.com','rss',1,'el','CY',ARRAY['national_flagship'],false),
('Offsite','offsite.com.cy','https://offsite.com.cy','rss',2,'el','CY',ARRAY['national_flagship'],false),
('Eswatini Observer','observer.org.sz','https://observer.org.sz','rss',1,'en','SZ',ARRAY['national_flagship'],false),
('Fiji One','fijione.tv','https://fijione.tv','rss',2,'en','FJ',ARRAY['national_flagship'],false),
('Islands Business Fiji','islandsbusiness.com','https://islandsbusiness.com','rss',1,'en','FJ',ARRAY['financial'],false),
('FBC News','fbcnews.com.fj','https://fbcnews.com.fj','rss',1,'en','FJ',ARRAY['national_flagship'],false),
('Mai TV','maitvfiji.com','https://maitvfiji.com','rss',2,'en','FJ',ARRAY['national_flagship'],false),
('Fiji Village','fijivillage.com','https://fijivillage.com','rss',1,'en','FJ',ARRAY['national_flagship'],false),
('Walesi Fiji','walesi.com.fj','https://walesi.com.fj','rss',3,'en','FJ',ARRAY['national_flagship'],false),
('Direct Infos Gabon','directinfosgabon.com','https://directinfosgabon.com','rss',2,'fr','GA',ARRAY['national_flagship'],false),
('Gabon Media Time','gabonmediatime.com','https://gabonmediatime.com','rss',2,'fr','GA',ARRAY['national_flagship'],false),
('Gabon Eco','gaboneco.com','https://gaboneco.com','rss',2,'fr','GA',ARRAY['financial'],false),
('Gabonews','gabonews.com','https://gabonews.com','rss',2,'fr','GA',ARRAY['national_flagship'],false),
('Info 241','info241.com','https://info241.com','rss',2,'fr','GA',ARRAY['national_flagship'],false),
('L Union Gabon','union.sonapresse.com','https://union.sonapresse.com','rss',1,'fr','GA',ARRAY['national_flagship'],false),
('Gabon Review','gabonreview.com','https://gabonreview.com','rss',1,'fr','GA',ARRAY['national_flagship'],false),
('Gambia News Today','gambianewstoday.com','https://gambianewstoday.com','rss',2,'en','GM',ARRAY['national_flagship'],false),
('Gambia Daily News','gambiana.com','https://gambiana.com','rss',3,'en','GM',ARRAY['national_flagship'],false),
('The Point','thepoint.gm','https://thepoint.gm','rss',1,'en','GM',ARRAY['national_flagship'],false),
('Kerr Fatou','kerrfatou.com','https://kerrfatou.com','rss',2,'en','GM',ARRAY['investigative'],false),
('The Standard Gambia','standard.gm','https://standard.gm','rss',1,'en','GM',ARRAY['national_flagship'],false),
('NOW Grenada','nowgrenada.com','https://nowgrenada.com','rss',1,'en','GD',ARRAY['national_flagship'],false),
('GBN Grenada','gbn.gd','https://gbn.gd','rss',2,'en','GD',ARRAY['national_flagship'],false),
('Guyana Times','guyanatimesgy.com','https://guyanatimesgy.com','rss',1,'en','GY',ARRAY['national_flagship'],false),
('Inews Guyana','inewsguyana.com','https://inewsguyana.com','rss',2,'en','GY',ARRAY['national_flagship'],false),
('News Source Guyana','newssourcegy.com','https://newssourcegy.com','rss',2,'en','GY',ARRAY['national_flagship'],false),
('Demerara Waves','demerarawaves.com','https://demerarawaves.com','rss',2,'en','GY',ARRAY['national_flagship'],false),
('Kaieteur News','kaieteurnewsonline.com','https://kaieteurnewsonline.com','rss',1,'en','GY',ARRAY['national_flagship'],false),
('Village Voice News','villagevoicenews.com','https://villagevoicenews.com','rss',3,'en','GY',ARRAY['national_flagship'],false),
('Television Jamaica TVJ','televisionjamaica.com','https://televisionjamaica.com','rss',1,'en','JM',ARRAY['national_flagship'],false),
('Our Today Jamaica','our.today','https://our.today','rss',2,'en','JM',ARRAY['financial'],false),
('Jamaica Information Service JIS','jis.gov.jm','https://jis.gov.jm','rss',2,'en','JM',ARRAY['national_flagship'],false),
('RJR News','radiojamaicanewsonline.com','https://radiojamaicanewsonline.com','rss',1,'en','JM',ARRAY['national_flagship'],false),
('Jamaica Star','jamaica-star.com','https://jamaica-star.com','rss',1,'en','JM',ARRAY['national_flagship'],false),
('Nationwide News Network','nationwideradiojm.com','https://nationwideradiojm.com','rss',1,'en','JM',ARRAY['national_flagship'],false),
('Pacific Islands News Association','pina.com.fj','https://www.pina.com.fj','rss',2,'en','KI',ARRAY['monitoring_source'],false),
('Pacific Daily News','guampdn.com','https://www.guampdn.com','rss',2,'en','KI',ARRAY['monitoring_source'],false),
('ABC News Pacific','abc.net.au','https://www.abc.net.au/news/pacific','rss',2,'en','KI',ARRAY['monitoring_source'],false),
('Public Eye Lesotho','publiceyenews.com','https://publiceyenews.com','rss',2,'en','LS',ARRAY['national_flagship'],false),
('Sunday Express Lesotho','sundayexpress.co.ls','https://sundayexpress.co.ls','rss',1,'en','LS',ARRAY['national_flagship'],false),
('LNS Lesotho News Service','gov.ls','https://gov.ls/news','rss',3,'en','LS',ARRAY['national_flagship'],false),
('Mihaaru','mihaaru.com','https://mihaaru.com','rss',1,'dv','MV',ARRAY['vernacular_dhivehi'],false),
('Sun MV Dhivehi','sun.mv','https://sun.mv','rss',1,'dv','MV',ARRAY['vernacular_dhivehi'],false),
('Channel News Maldives','cnm.mv','https://cnm.mv','rss',3,'dv','MV',ARRAY['national_flagship'],false),
('AVAS','avas.mv','https://avas.mv','rss',2,'dv','MV',ARRAY['national_flagship'],false),
('The Shift News','theshiftnews.com','https://theshiftnews.com','rss',2,'en','MT',ARRAY['investigative'],false),
('Bay TV Malta','bay.com.mt','https://bay.com.mt','rss',3,'en','MT',ARRAY['national_flagship'],false),
('Lovin Malta','lovinmalta.com','https://lovinmalta.com','rss',2,'en','MT',ARRAY['digital_native'],false),
('L-Orizzont','l-orizzont.com','https://l-orizzont.com','rss',2,'mt','MT',ARRAY['vernacular_maltese'],false),
('Malta Independent','independent.com.mt','https://independent.com.mt','rss',1,'en','MT',ARRAY['national_flagship'],false),
('Gozo News','gozonews.com','https://gozonews.com','rss',2,'en','MT',ARRAY['regional'],false),
('Top FM','topfm.mu','https://topfm.mu','rss',2,'fr','MU',ARRAY['national_flagship'],false),
('Le Defi Quotidien','defimedia.info','https://defimedia.info','rss',1,'fr','MU',ARRAY['national_flagship'],false),
('Capital Mauritius','capital.mu','https://capital.mu','rss',2,'fr','MU',ARRAY['financial'],false),
('Le Mauricien','lemauricien.com','https://lemauricien.com','rss',1,'fr','MU',ARRAY['national_flagship'],false),
('Mauritius Times','mauritiustimes.com','https://mauritiustimes.com','rss',2,'en','MU',ARRAY['english_language'],false),
('Inside.News Mauritius','inside.news','https://inside.news','rss',2,'en','MU',ARRAY['english_language'],false),
('5 Plus Dimanche','5plus.mu','https://5plus.mu','rss',2,'fr','MU',ARRAY['national_flagship'],false),
('Lalit Movement','lalitmauritius.org','https://lalitmauritius.org','rss',3,'en','MU',ARRAY['political'],false),
('NBC','nbc.na','https://nbc.na','rss',1,'en','NA',ARRAY['national_flagship'],false),
('Informante','informante.web.na','https://informante.web.na','rss',2,'en','NA',ARRAY['national_flagship'],false),
('Namibia Sun','namibiansun.com','https://namibiansun.com','rss',1,'en','NA',ARRAY['national_flagship'],false),
('Confidente Namibia','confidentenamibia.com','https://confidentenamibia.com','rss',2,'en','NA',ARRAY['national_flagship'],false),
('Namibia Economist','economist.com.na','https://economist.com.na','rss',2,'en','NA',ARRAY['financial'],false),
('Allgemeine Zeitung','az.com.na','https://az.com.na','rss',2,'de','NA',ARRAY['vernacular_german'],false),
('Windhoek Observer','observer.com.na','https://observer.com.na','rss',2,'en','NA',ARRAY['national_flagship'],false),
('Republikein','republikein.com.na','https://republikein.com.na','rss',2,'af','NA',ARRAY['vernacular_afrikaans'],false),
('Pacific Islands Times','pacificislandtimes.com','https://www.pacificislandtimes.com','rss',2,'en','NR',ARRAY['monitoring_source'],false),
('The Observer SKN','thestkittsnevisobserver.com','https://thestkittsnevisobserver.com','rss',1,'en','KN',ARRAY['national_flagship'],false),
('SKN Vibes','sknvibes.com','https://sknvibes.com','rss',1,'en','KN',ARRAY['national_flagship'],false),
('St Lucia Star','stluciastar.com','https://stluciastar.com','rss',2,'en','LC',ARRAY['national_flagship'],false),
('St Lucia News Online','stlucianewsonline.com','https://stlucianewsonline.com','rss',1,'en','LC',ARRAY['national_flagship'],false),
('The Voice St Lucia','thevoiceslu.com','https://thevoiceslu.com','rss',1,'en','LC',ARRAY['national_flagship'],false),
('The Vincentian','thevincentian.com','https://thevincentian.com','rss',1,'en','VC',ARRAY['national_flagship'],false),
('iWitness News','iwnsvg.com','https://iwnsvg.com','rss',1,'en','VC',ARRAY['investigative'],false),
('Searchlight SVG','searchlight.vc','https://searchlight.vc','rss',1,'en','VC',ARRAY['national_flagship'],false),
('Samoa Global News','samoaglobalnews.com','https://samoaglobalnews.com','rss',2,'en','WS',ARRAY['national_flagship'],false),
('Talamua Online','talamua.com','https://talamua.com','rss',1,'en','WS',ARRAY['national_flagship'],false),
('Seychelles Weekly','seychellesweekly.com','https://seychellesweekly.com','rss',2,'en','SC',ARRAY['national_flagship'],false),
('Seychelles Nation','nation.sc','https://nation.sc','rss',1,'en','SC',ARRAY['national_flagship'],false),
('SIBC Online','sibconline.com.sb','https://sibconline.com.sb','rss',2,'en','SB',ARRAY['national_flagship'],false),
('Island Sun','theislandsun.com.sb','https://theislandsun.com.sb','rss',1,'en','SB',ARRAY['national_flagship'],false),
('Solomon Times Online','solomontimes.com','https://solomontimes.com','rss',1,'en','SB',ARRAY['national_flagship'],false),
('Tonga Broadcasting Commission','tbc.to','https://tbc.to','rss',2,'en','TO',ARRAY['national_flagship'],false),
('Matangi Tonga','matangitonga.to','https://matangitonga.to','rss',1,'en','TO',ARRAY['national_flagship'],false),
('Talanoa o Tonga','talanoaotonga.to','https://talanoaotonga.to','rss',3,'en','TO',ARRAY['national_flagship'],false),
('IzzSo Trinidad','izzso.com','https://izzso.com','rss',3,'en','TT',ARRAY['national_flagship'],false),
('TV6 Trinidad','tv6tnt.com','https://tv6tnt.com','rss',1,'en','TT',ARRAY['national_flagship'],false),
('Power 102 FM','power102fm.com','https://power102fm.com','rss',2,'en','TT',ARRAY['national_flagship'],false),
('CNC3','cnc3.co.tt','https://cnc3.co.tt','rss',1,'en','TT',ARRAY['national_flagship'],false),
('Trinidad Express','trinidadexpress.com','https://trinidadexpress.com','rss',1,'en','TT',ARRAY['national_flagship'],false),
('Newsday Trinidad','newsday.co.tt','https://newsday.co.tt','rss',1,'en','TT',ARRAY['national_flagship'],false),
('Vanuatu Independent','vanuatuindependent.com','https://vanuatuindependent.com','rss',2,'en','VU',ARRAY['national_flagship'],false),
('Vanuatu Business Review','vbr.vu','https://vbr.vu','rss',3,'en','VU',ARRAY['financial'],false),
('VBTC','vbtc.vu','https://vbtc.vu','rss',2,'en','VU',ARRAY['national_flagship'],false),
('News Diggers','diggers.news','https://diggers.news','rss',1,'en','ZM',ARRAY['national_flagship'],false),
('The Post Zambia','postzambia.com','https://postzambia.com','rss',2,'en','ZM',ARRAY['national_flagship'],false),
('Mwebantu','mwebantu.com','https://mwebantu.com','rss',2,'en','ZM',ARRAY['national_flagship'],false),
('Open Zambia','openzambia.com','https://openzambia.com','rss',3,'en','ZM',ARRAY['investigative'],false),
('Zambia Reports','zambiareports.news','https://zambiareports.news','rss',2,'en','ZM',ARRAY['national_flagship'],false),
('Zambia Monitor','zambiamonitor.com','https://zambiamonitor.com','rss',2,'en','ZM',ARRAY['national_flagship'],false),
('ZNBC','znbc.co.zm','https://znbc.co.zm','rss',1,'en','ZM',ARRAY['national_flagship'],false)
ON CONFLICT (domain) DO NOTHING;
SELECT count(*) AS after_total, count(*) FILTER (WHERE is_active=false AND created_at > now() - interval '10 minutes') AS staged_batch FROM sources;
COMMIT;
\echo '### per-country staged this batch:'
SELECT country, count(*) FROM sources WHERE is_active=false AND source_type='rss' AND created_at > now() - interval '10 minutes' GROUP BY 1 ORDER BY 1;
